[env]
TERM = "xterm-256color"

[scrolling]
history = 5000

[terminal.shell]
program = "/usr/bin/zsh"

[window]
decorations = "full"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6

[general]
live_config_reload = true
working_directory = "None"
import = ["/home/ciara/.dotfiles/alacritty/theme.toml", "/home/ciara/.dotfiles/alacritty/fonts.toml", "/home/ciara/.dotfiles/alacritty/keybindings.toml", "/home/ciara/.dotfiles/alacritty/cursor.toml"]

[terminal]
