
[font]
size = 12

[font.bold]
family = "Ark Pixel 16px M latin"
style = "Bold"

[font.bold_italic]
family = "Ark Pixel 16px M latin"
style = "Bold Italic"

[font.italic]
family = "Ark Pixel 16px latin"
style = "Italic"

[font.normal]
family = "Ark Pixel 16px M latin"
style = "Regular"

[font.offset]
x = 1
y = 1

[colors]
draw_bold_text_with_bright_colors = true
